### ISSUE TITLE
重复加载

### ISSUE THREAD

**Issue by WordZzzz** [Mashiro-Sorata/APlayer-Controler#1]
请问，该插件是否可以在同一域名下不进行重复加载呢？比如当前页面播放了音乐，点一个链接之后，音乐重新开始播放了，这样体验感觉不是很好，毕竟有些强迫症······如果切换界面不影响播放那就好了，我这个门外汉的问题不知道水不水······

**Comment by Mashiro-Sorata** [comment]
抱歉回复太迟了……APC只是一个控制AP播放器的小插件，这个需要AP播放器功能的支持。如果不想重新加载只有在新窗口中打开了……
